# Generated by Django 4.2.8 on 2023-12-14 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_ativo"),
        ("livro", "0007_categoria_livros_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="livros",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="usuarios.usuario",
            ),
            preserve_default=False,
        ),
    ]
