# Generated by Django 4.2.8 on 2023-12-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="ativo",
            field=models.BooleanField(default=False),
        ),
    ]
